
name: mv-directory-app
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: antongorshkov/chatlist-nectar
  name: web
  envs:
    - key: VITE_API_URL
      value: https://machu-server-app-2tn7n.ondigitalocean.app
      scope: BUILD_TIME
