-- INSERT ... ON CONFLICT consumes an identity value even when the row already
-- exists, and the listener refreshes a group on every message, so group
-- reference numbers grew in large jumps. Update first and insert only new
-- groups, then renumber existing groups once in the order they were seen.

CREATE OR REPLACE FUNCTION public.upsert_whatsapp_group(p_group_jid TEXT, p_group_name TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_name TEXT := NULLIF(left(btrim(COALESCE(p_group_name, '')), 200), '');
  v_enabled BOOLEAN;
BEGIN
  UPDATE public.whatsapp_groups AS groups SET
    name = COALESCE(v_name, groups.name),
    updated_at = CASE WHEN v_name IS NOT NULL AND v_name IS DISTINCT FROM groups.name
      THEN now() ELSE groups.updated_at END
  WHERE groups.jid = p_group_jid
  RETURNING groups.enabled INTO v_enabled;
  IF FOUND THEN
    RETURN v_enabled;
  END IF;

  BEGIN
    INSERT INTO public.whatsapp_groups (jid, name)
    VALUES (p_group_jid, v_name)
    RETURNING enabled INTO v_enabled;
  EXCEPTION WHEN unique_violation THEN
    -- Another listener event inserted the group concurrently.
    SELECT groups.enabled INTO v_enabled
    FROM public.whatsapp_groups AS groups WHERE groups.jid = p_group_jid;
  END;
  RETURN v_enabled;
END;
$$;

ALTER TABLE public.whatsapp_groups ALTER COLUMN ref SET GENERATED BY DEFAULT;

UPDATE public.whatsapp_groups SET ref = -ref;
UPDATE public.whatsapp_groups AS groups SET ref = ordered.position
FROM (
  SELECT jid, row_number() OVER (ORDER BY first_seen_at, jid) AS position
  FROM public.whatsapp_groups
) AS ordered
WHERE groups.jid = ordered.jid;

SELECT setval(
  pg_get_serial_sequence('public.whatsapp_groups', 'ref'),
  GREATEST((SELECT max(ref) FROM public.whatsapp_groups), 1),
  (SELECT count(*) > 0 FROM public.whatsapp_groups)
);

ALTER TABLE public.whatsapp_groups ALTER COLUMN ref SET GENERATED ALWAYS;

REVOKE ALL ON FUNCTION public.upsert_whatsapp_group(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.upsert_whatsapp_group(TEXT, TEXT) TO machu_listener, service_role;
